apiVersion: falco.org/v1alpha1
kind: FalcoEvent
metadata:
  name: delete-pod-on-shell-detection
  namespace: falco
spec:
  rule: Terminal shell in container
  priority: Warning
  output: Shell spawned in container (user=%user.name command=%proc.cmdline container=%container.id)
  match:
    outputFields:
      container.image.repository: "*"
  action:
    kubernetes:
      deletePod: true
