apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falcosidekick-response
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: falco
    server: https://kubernetes.default.svc
  project: platform-engineering
  source:
    repoURL: https://github.com/Sohummnm/gitops-ArgoCD.git
    targetRevision: HEAD
    path: cac/falco/charts/falcosidekick
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
