apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falcoevent-trigger
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: platform-engineering
  source:
    repoURL: https://github.com/Sohummnm/gitops-ArgoCD.git
    targetRevision: HEAD 
    path: cac/falco/charts/falcosidekick/falcoevent
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true