apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: falcoevents.falco.org
spec:
  group: falco.org
  names:
    kind: FalcoEvent
    listKind: FalcoEventList
    plural: falcoevents
    singular: falcoevent
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                rule:
                  type: string
                priority:
                  type: string
                output:
                  type: string
                time:
                  type: string
