apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-engineering
  namespace: argocd
spec:
  description: Project for platform engineering apps
  sourceRepos:
    - '*'  
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
