# Istio root application for ArgoCD

apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata: 
  name: istio-root
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave = "3"
spec:
  project: platform-engineering
  source:
    repoURL: https://github.com/Sohummnm/gitops-ArgoCD.git
    targetRevision: HEAD
    path: cac/argocd-crd/istio
  destination:
    server: https://kubernetes.default.svc  
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
